### ISSUE TITLE
複数ロボットというよりシステム統合では？

### ISSUE THREAD

**Issue by haraisao** [YutaNaito/CooperativeController#1]
概要を拝見しましたが、複数ロボットの協調というより複数のロボットシステムの統合なのではないでしょうか？
複数のロボットシステムの統合の場合に、作業させる対象や作業内容に応じて、協調動作の閾値やパラメータの適応が求められると思います。
コードを拝見しましたが、すべて決め打ちのようですが、他の用途（同じPick-and-Placeでも対象物の素材や大きさで行動が変わると思います）で使う場合にどうすればよいかの考察とコードの柔軟性があれば良いと思います。
要は、行動のアービトレーションが書きやすいフレームワークまで拡張して欲しいと思います。

**Comment by YutaNaito** [comment]
ご指摘ありがとうございます。仰る通り複数のロボットシステムの統合に近いです。また、閾値やパラメータもこちらの決め打ちになってしまっています。柔軟性の改善など善処していきたいと思います。
