### ISSUE TITLE
利用手順について

### ISSUE THREAD

**Issue by Nobu19800** [YutaNaito/CooperativeController#2]
利用手順を読んだ限りでは使い方がよく分かりません。CooperativeControllerには見たところ実行ファイルは含まれていないようなのでビルドの手順などの説明が必要になりますし、他のRTCについても入手先や利用方法の説明があったほうが親切だと思います。

**Comment by YutaNaito** [comment]
ご指摘ありがとうございます。ビルドの手順は，マニュアルとマークダウンに追加で記載しアップロードさせていただきました。他のRTCについては，コードが汚いため少し整理し，間に合えばサンプルとして順次アップロードさせていただきます。
